FROM golang:1.24.1 AS builder
WORKDIR /app
COPY go.mod ./
COPY proxy/proxy.go ./
COPY main.go ./
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o proxy main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/proxy .
EXPOSE 8888
CMD ["./proxy"]